### ISSUE TITLE
Problem with ANSI data

### ISSUE THREAD

**Issue by rferraton** [KeshiaRose/Basic-CSV-WDC#11]
Hello 
i have a source with ANSI code page data and the result is not display correctly

Source data :
https://files.data.gouv.fr/lcsqa/concentrations-de-polluants-atmospheriques-reglementes/temps-reel/2021/FR_E2_2021-09-14.csv

Would it be possible to add the code page of the source data in the advanced section ?

**Comment by KeshiaRose** [comment]
Hi @rferraton, I've now added an option to include an encoding. In your example, you would use `iso-8859-1`. Hope this works for you!
-Keshia

**Comment by rferraton** [comment]
Yes it work pretty well ! :+1: 
Thanks a lot !!

PS : thank to you csv web connector these workbook is refreshed easily each week :
https://public.tableau.com/app/profile/apfr5254/viz/IncidenceCOVIDFranceDpartementettranchesdage/FranceCOVID-IncidencevsDcsRanimationsetHospitalisations

Romain
