### ISSUE TITLE
Requesting License Clarification. No license is assumed as default copyright law. For remixing request review consideration as labeling MIT, BSD, unlicensed, or creative commons

### ISSUE THREAD

**Issue by bryanhurricane** [KeshiaRose/Basic-CSV-WDC#12]

**Comment by KeshiaRose** [comment]
Updated thanks! Would love to see any remixes/updates you make :)

**Comment by bryanhurricane** [comment]
You are awesome. Thank you so much! Your connectors and blogs give me so many ideas.  Looking forward to making some spin offs and sharing some of my own works soon.
