### ISSUE TITLE
Adding separator option

### ISSUE THREAD

**Issue by miguelTukan** [KeshiaRose/Basic-CSV-WDC#14]
Hi!

Thanks for creating this tool. I was wondering if you'd consider adding an option to specify the separator use in the CSV file, i.e. pipes or semicolons...

Again thanks for creating this

**Comment by KeshiaRose** [comment]
Hi @miguelTukan, thanks for the feedback!! There is actually an option to use a custom delimiter already available! 🙌🏾 Click on "Advanced +" and you'll see where you can change this and a few more settings. This does make me think though that perhaps other people may not have noticed this. I'll make sure to update the readme with more information so it's easier to find!
