### ISSUE TITLE
CSV with Semi-colons

### ISSUE THREAD

**Issue by anthelix** [KeshiaRose/Basic-CSV-WDC#7]
it works with a csv file and commas but not with semicolons. 
The connector is great and that's exactly what I need. Could help me? 
thanks a lot!

**Comment by KeshiaRose** [comment]
Hi @anthelix, I've added a new option to the "Advanced" section. You can now specify a delimiter and that will be used instead of a comma. Let me know if it works for you! If not, then please share the data source you are trying to connect to and re-open this issue.
-Keshia
