### ISSUE TITLE
URL is not valid

### ISSUE THREAD

**Issue by Gibbs38** [KeshiaRose/Basic-CSV-WDC#8]
Hi Rose,
Thanks for the app., that's exactly what I was lookinf for, although I am struggling with the URL which I share with you.
In the browser I get the file 18k... not too big?
I can't figure out the issue.
https://www.xpfi.online/Data/0001/Clients.csv
Could you help?
Thanks in advance.
Frédéric.

**Comment by KeshiaRose** [comment]
Oh I think the .online was being caught as an error in my URL validation regex. I've changed it now so it just shows a warning if it doesn't match. Try it out again, and if it doesn't work for you please re-open!
